### PR TITLE
Update to database contents.

### PR DESCRIPTION
**Pull request by zcskywire2**
This update would add support to the database for Ryzen 3, Threadripper and Epyc product lines. Sorry for the large numbers of commits, was learning to use GitHub (also was using the to save files while i was at work on mobile...)

### CODE REVIEW

**Comment by markasoftware** [comment]
Great, overall looks pretty good. It's a bit late here so I'll probably be able to review and merge this tomorrow.

**Comment by markasoftware** [comment]
Okay, I've found a few problems so far which are worth mentioning:

* Frequencies should be written like GHz or MHz, not Ghz or Mhz, this affects the algorithm that compares values to determine which is better. Capitalization is important.
* Things like `32? MiB` also mess up the comparer. It's better to write `TBA` instead if you don't know.
* I see `XFR Frequency: N/A` in some of your files. This is not necessary, N/A is the default. You can just leave out `XFR Frequency` altogether
* Same goes for `Unlocked: false`. Leave it out unless you are overriding something you inherited. It will default to false. You might want to look around in `src/js/row-data.js`
* Threadripper and Epyc should go under the "ZEN FAMILY" header. I'm not super familiar with the low level architectural stuff in CPUs so if they really should be separate let me know.
* Same goes for Epyc CPUs saying "Epyc" as the architecture, I think they still use the Zen architecture (but I may be wrong here) but it says Epyc under architecture.
* Additionally, Threadripper probably shouldn't even have its own section under the "Select Architecture" screen, I think it should just be a header on the Ryzen page above R7.

I really appreciate what you've done by adding these parts, and if you don't get to fixing these I'll be happy to do it myself, it just might take a bit longer.

**Comment by zcskywire2** [comment]
I can certainly go through the yaml files and tighten up those minor issues. Most of the extra lines are there as I just reverse engieered how they function.  As for why I layed out the processors as I did, many people do not know the names of the mirco-archs. Most people will know the product linup that the processors are a member of. This is mainly how the ark.intel site is layed out. Futhermore it reduces the clutter on the later pages. With all the zen based CPUs on one page you end up with over 22 processor sku's. Some mirco-archs will have even more  such as bulldozer. Having it done this way will speed up the search for a particular sku and will make it easier to find a ski for a non technical person. And even though the arch family is no longer listed the mirco arch is.

**Comment by zcskywire2** [comment]
I've gone through all the yaml files that I created and checked them for the items listed above fixing all the above. I've also continued adding processor families by adding the AMD FX Bulldozer CPUs.

**Comment by markasoftware** [comment]
Okay, looks good. I'll probably make a few final changes to the layout of everything before merging this (hopefully later today), and I'll need to make a small change in the main codebase to have it support "TBA" values properly. Thanks!

**Comment by zcskywire2** [comment]
While I'm thinking about it, what does the database support in the way of dates. Mainly because some of the CPUs added  haven't had a release date announced. Others that could be added only have their relase date as a quarter. Ex q4 2016. I don't know how you would want those ones filled in for the date. Also started adding support for the entire Phenom II processor linup,  so if you have any thoughts how you want them later out let me know. Currently it's broken down on the main screen into X6 header and then it's familes, x4 header then is familes , x3 ..., X2...   Either way I'mma just keep moving forward and adding more to the database

**Comment by markasoftware** [comment]
Currently dates only allow strings in yyyy-mm-dd format. Adding support for quarters is a good idea. I've opened an issue for this to keep track of it and remind myself.

**Comment by markasoftware** [comment]
Changes are live!

**Comment by zcskywire2** [comment]
I've now got the full set of Phenom II updates completed. Just trying to fix the conflict between the branches and then you'll be getting another pull request.

**Pull request merged**
