### PR TITLE
Database update for full Phenom II processor family support

### PR DESCRIPTION
**Pull request by zcskywire2**
Title pretty much covers it all.

### CODE REVIEW

**Comment by zcskywire2** [comment]
After the sync to the main branch, site page no longer displays anything with the phenom II updates. Currently working to figure out why. Will keep posted

**Comment by zcskywire2** [comment]
Turns out the search update does not support a CPU whose human name lacks a alphabetical character. Many of the Phenom II SKUs lack that alphabetical character and they were preventing the database from being loaded, even though it compiles fine.

**Comment by zcskywire2** [comment]
Found the issue. Turns out with the newer updates, probably the search one, that human names for CPUs cannot consist of only numeric characters and spaces. Phenom II CPUs mainly consist of SKUs that only contain numbers and they were causing the issue.

**Comment by markasoftware** [comment]
Hey, once again thanks for the great work, it's coming along a lot quicker than I would have expected it to have. However, the names of the CPUs here is not great. The name and humanName of each CPU should be enough to identify the CPU without knowing what category it is in or anything. A lot of the CPUs in here have barely anything to their name, such as just `545` or `B75`. It is important that a name is enough to identify a CPU so that in search results it is clear what it is. Perhaps, for example, you could rename `545` to `X2 545` or something like that, just give it a bit of context.

One more thing is that, in general (not just on this repo), it's generally recommended to make a new git branch in the forked repo for every PR. You can see that all the old commits are appearing here because of this. I think it will still work fine though, hopefully.

**Comment by markasoftware** [comment]
I'm creating a new "beta" branch, which is where newish code will go and it will get a new subdomain. Only once features are relatively well-tested will they get to go on the main domain. I'm planning to have most PRs go to this new "beta" branch, including this one. So, I'm closing it, and you should re-open it pointing at the beta branch. Thanks!

**Pull request closed without merging**
