### PR TITLE
Improve README.md on Ubuntu/Debian

### PR DESCRIPTION
**Pull request by LittleVulpix**
Version of nodejs on Ubuntu 16.xx is too old for build to succeed.
Installation of the latest nodejs taken from https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
Also fixed a typo.

### CODE REVIEW

**Comment by markasoftware** [comment]
Debian != Linux. I personally think it's best to leave it up to people to figure out how to get the latest version of Node, and `nvm` is probably a better idea than using distro packages for this. If you want to add a separate section to the readme for setting up under certain distros, that's fine, but i don't think it should go in the main instructions.

**Comment by LittleVulpix** [comment]
Hmm, I agree. It took me a while to get this set up because of the failing dependencies - mostly because the manual does not provide any prerequisites. I suppose we could instead note that the latest version of Node is required. I was not aware of the fact that the "latest" version that ships with and is available in the Ubuntu repos is 4.2.6 (or something ancient like that), and it took me a while to figure out that a newer version is required, and then how to get it. I could create a pull request that would be something like - prerequisites: Nodejs (latest version from <site>) or "At least version 8.4.xx" ?

**Comment by LittleVulpix** [comment]
Yeah I'll do that. I think that's more reasonable.

**Comment by markasoftware** [comment]
Great. Also, if you want to join us on Discord, which is where most of the development talk happens, here's the link: https://discord.gg/xfVHZAb

**Pull request closed without merging**
